src/AppBundle/Entity/Post.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\PostRepository")
 * @ORM\HasLifecycleCallbacks
 *
 * @Vich\Uploadable
 * @ApiResource
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Assert\Type(type="string", message="post.title.type")
     *
     * @var string
     */
    private $title;

    /**
     * @Assert\Image(
     *     maxSize="2M",
     *     maxSizeMessage="Size allowed: up to 2M",
     *     maxWidth="1920",
     *     maxWidthMessage="The max width is 1920px",
     *     maxHeight="1080",
     *     maxHeightMessage="The max height is 1080px",
     *     mimeTypes = {"image/jpeg", "image/png", "image/gif"},
     *     mimeTypesMessage = "Please upload a valid image. The supported formats are JPEG, PNG and GIF"
     * )
     * @Vich\UploadableField(mapping="post_image", fileNameProperty="image_name")
     *
     * @var File
     */
    private $image_file;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $image_name;

    /**
     * Many Features have One Product.
     *
     * @ORM\ManyToOne(targetEntity="Thread", inversedBy="posts")
     * @ORM\JoinColumn(name="thread_id", referencedColumnName="id")
     */
    private $thread;

    /**
     * @ORM\Column(name="created_datetime",type="datetime")
     *
     * @var \DateTime
     */
    private $created_datetime;

    /**
     * @ORM\Column(name="updated_datetime", type="datetime")
     *
     * @var \DateTime
     */
    private $updated_datetime;

    public function __construct()
    {
        $this->created_datetime = new \DateTime('now');
        $this->updated_datetime = new \DateTime('now');
    }

    /**
     * @return mixed
     */
    public function getThread()
    {
        return $this->thread;
    }

    /**
     * @param Thread $thred
     *
     * @return $this
     */
    public function setThread(Thread $thred)
    {
        $this->thread = $thred;

        return $this;
    }

    /**
     * @ORM\PreUpdate
     */
    public function onPreUpdate()
    {
        $this->updated_datetime = new \DateTime('now');
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedDatetime()
    {
        return $this->updated_datetime;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedDatetime()
    {
        return $this->created_datetime;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param $value
     *
     * @return $this
     */
    public function setTitle($value)
    {
        $this->title = $value;

        return $this;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return $this
     */
    public function setImageFile(File $image = null)
    {
        $this->image_file = $image;

        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated_datetime = new \DateTime('now');
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->image_file;
    }

    /**
     * @param string $image_name
     *
     * @return $this
     */
    public function setImageName($image_name)
    {
        $this->image_name = $image_name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getImageName()
    {
        return $this->image_name;
    }
}

src/AppBundle/Resources/views/app/thread_view.html.twig
{% extends 'AppBundle:template:template.html.twig' %}

{% block main_container %}

  <div class="container">

    <div class="row">
      <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12 ">

        {% include 'AppBundle:includes:flash_messages.html.twig' %}

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
              <div class="col-lg-4 text-left">{{ 'Posts'|trans }}: <strong>{{ posts|length }}</strong></div>
              <div class="col-lg-4 text-center">
                <a class="btn btn-lg btn-default" href="{{ path('export_thread', { 'id' : thread.id }) }}" >{{ 'Export'|trans }}</a>
              </div>
              <div class="col-lg-4 text-right">{{ 'Views'|trans }}: <strong><span id="views-counter" data-url="{{ path('api_threads_get_item',{'id':1,'_format':'json'}) }}">{{ thread.getViews }}</span></strong></div>
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            {{ form(post_form) }}
          </div>
        </div>

        {% if posts is iterable %}
          <div class="row">

          {% for post in posts %}

            <div class="col-lg-12">
              <div class="panel panel-info">
                <div class="panel-body text-center">

                  {% if post.getTitle is not null and post.getTitle|length > 0 %}
                    <p><strong>{{ post.getTitle }}</strong></p>
                  {% endif %}

                  {% if post.imageFile is not null %}
                    <img src="{{ path('load_post_image', { 'id' : post.id }) }}" class="img-responsive center-block" alt="Post {{ post.getId }} image" />
                  {% else %}
                    {% trans %}No image registered{% endtrans %}
                  {%  endif %}
                </div>
              </div>
            </div>

          {% endfor %}

          </div>
        {% endif %}

      </div>
    </div>

  </div>


{% endblock %}